In [1]:
import pandas as pd

from python lists

In [12]:
data = [
["Alice",35],
["Bob",30],
["Charlie",35]
]
df = pd.DataFrame(data, columns=["Name","Age"], index=["q","w","r"])
df

      Name  Age
q    Alice   35
w      Bob   30
r  Charlie   35

In [13]:
df.index=["a","b","c"]
df

      Name  Age
a    Alice   35
b      Bob   30
c  Charlie   35

From Dictionary of Lists

In [15]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
data

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}

From NumPy Arrays

In [18]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
# df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

In [7]:
df = pd.read_csv("data.csv")
df

      Name School  Marks
0     upma   upes     99
1   ruhani   upes     98
2  rimjhim     sr     97
3    vidya  bihar     96
4  aarushi  bihar     95

In [9]:
import pandas as pd
pd.read_csv("data.csv", usecols=["Name", "School","Marks"])

      Name School  Marks
0     upma   upes     99
1   ruhani   upes     98
2  rimjhim     sr     97
3    vidya  bihar     96
4  aarushi  bihar     95

In [12]:
df = pd.read_csv("data.csv")
df

      Name School  Marks
0     upma   upes     99
1   ruhani   upes     98
2  rimjhim     sr     97
3    vidya  bihar     96
4  aarushi  bihar     95