In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data_transforming.csv")

In [3]:
df

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7
8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9

In [4]:
df.sort_values("Year")

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [5]:
df.sort_values(["Year", "IMDb Rating"])

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [6]:
df.sort_values("Year", ascending=False)

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0

In [7]:
df2 = df.sort_values(["Year","IMDb Rating"]).copy()

In [8]:
df2

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [9]:
df2.reset_index()

,index,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
0,8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
1,0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
2,1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
3,9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
4,3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
5,4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
6,10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
7,6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
8,5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
9,2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
10,7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [12]:
df2.reset_index(drop=True)

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
0,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
1,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
2,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
3,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
4,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
5,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
6,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
7,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
8,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
9,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
10,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [23]:
df2.reset_index(drop=True,inplace=True)#in[lace krne se jo original data frame h whi update ho jata h

In [24]:
df2

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
0,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
1,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
2,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
3,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
4,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
5,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
6,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9
7,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
8,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
9,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
10,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [37]:
df2["Rank"] = df2["IMDb Rating"].rank(ascending=False)

In [38]:
 df2

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating,Rank
0,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0,8.0
1,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3,4.0
2,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0,8.0
3,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0,8.0
4,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0,8.0
5,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2,5.0
6,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9,11.0
7,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0,8.0
8,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0,2.5
9,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0,2.5
10,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7,1.0

In [39]:
cols = ["Year"] + [col for col in df.columns if col != "Year"]
df = df[cols]

In [40]:
df

,Year,Movie,Lead Actor(s),Genre,Worldwide Gross (INR Cr),IMDb Rating
0,2016,Dangal,Aamir Khan,Sports Biopic,2020,8.3
1,2017,Baahubali 2: The Conclusion,Prabhas,Epic / Historical,1810,8.0
2,2024,Pushpa: The Rule – Part 2,Allu Arjun,Action / Drama,1742,9.0
3,2022,RRR,"Jr. NTR, Ram Charan",Period Action,1230,8.0
4,2022,KGF Chapter 2,Yash,Action Thriller,1215,8.2
5,2023,Jawan,Shah Rukh Khan,Action Thriller,1160,9.0
6,2023,Pathaan,Shah Rukh Khan,Spy Action,1055,8.0
7,2024,Kalki 2898 AD,Prabhas,Sci-Fi / Epic,1042,9.7
8,2015,Bajrangi Bhaijaan,Salman Khan,Drama / Social,920,8.0
9,2017,Secret Superstar,Aamir Khan,Musical / Family,966,8.0
10,2023,Animal,Ranbir Kapoor,Action Crime,915,6.9