In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data_transforming.csv")

In [3]:
df

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
1,Baahubali 2: The Conclusion,Prabhas,2017,Epic / Historical,1810,8.0
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
3,RRR,"Jr. NTR, Ram Charan",2022,Period Action,1230,8.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
6,Pathaan,Shah Rukh Khan,2023,Spy Action,1055,8.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7
8,Bajrangi Bhaijaan,Salman Khan,2015,Drama / Social,920,8.0
9,Secret Superstar,Aamir Khan,2017,Musical / Family,966,8.0
10,Animal,Ranbir Kapoor,2023,Action Crime,915,6.9

In [6]:
df = df[df["IMDb Rating"]>8.0]

In [7]:
df

,Movie,Lead Actor(s),Year,Genre,Worldwide Gross (INR Cr),IMDb Rating
0,Dangal,Aamir Khan,2016,Sports Biopic,2020,8.3
2,Pushpa: The Rule – Part 2,Allu Arjun,2024,Action / Drama,1742,9.0
4,KGF Chapter 2,Yash,2022,Action Thriller,1215,8.2
5,Jawan,Shah Rukh Khan,2023,Action Thriller,1160,9.0
7,Kalki 2898 AD,Prabhas,2024,Sci-Fi / Epic,1042,9.7

In [9]:
df.to_csv("data_updates.csv",index=False)

In [3]:
import pandas as pd

In [7]:
df1 = pd.read_json("data.json")
df1

   id   name                                  address
0   1  Alice   {'city': 'Delhi', 'zipcode': '110001'}
1   2    Bob  {'city': 'Mumbai', 'zipcode': '400001'}

In [8]:
data = [
{"id": 1, "name": "Alice", "address":{"city": "Delhi", "zipcode": "110001"}},
{"id": 2, "name": "Bob", "address": {"city": "Mumbai", "zipcode": "400001"}}
]

In [9]:
data

[{'id': 1, 'name': 'Alice', 'address': {'city': 'Delhi', 'zipcode': '110001'}},
 {'id': 2, 'name': 'Bob', 'address': {'city': 'Mumbai', 'zipcode': '400001'}}]

In [14]:
df1 = pd.json_normalize(data)
df1

   id   name address.city address.zipcode
0   1  Alice        Delhi          110001
1   2    Bob       Mumbai          400001

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               2 non-null      int64
 1   name             2 non-null      object
 2   address.city     2 non-null      object
 3   address.zipcode  2 non-null      object
dtypes: int64(1), object(3)
memory usage: 192.0+ bytes